name: Reuse Warmed Cache

on:
  workflow_dispatch:

jobs:
  reuse-cache:
    runs-on: self-hosted

    env:
      MAVEN_REPO: /home/brentlipke/actions-runner/seeds/m2-warm-cache

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare temp folders
      run: |
        mkdir -p "${RUNNER_TEMP}/jansi-${GITHUB_RUN_ID}"
        mkdir -p "${RUNNER_TEMP}/tmp-${GITHUB_RUN_ID}"

    - name: Build using warmed Maven cache
      run: |
        export MAVEN_OPTS="
          -Dmaven.repo.local=$MAVEN_REPO
          -Djansi.tmpdir=${RUNNER_TEMP}/jansi-${GITHUB_RUN_ID}
          -Djava.io.tmpdir=${RUNNER_TEMP}/tmp-${GITHUB_RUN_ID}
        "
        mvn -B clean verify
