name: return Maven version
on: workflow_dispatch

jobs:
  build:
    runs-on: rhel-laptop-default
    env:
      MAVEN_HOME: /home/brentlipke/actions-runner/_work/_tool/apache-maven-3.9.9
      PATH: /home/brentlipke/actions-runner/_work/_tool/apache-maven-3.9.9/bin:${{ env.PATH }}
      MAVEN_OPTS: "-Dmaven.repo.local=${{ runner.temp }}/m2repo-${{ github.workflow_id }} -Djansi.tmpdir=${{ runner.temp }}"
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: maven
    - name: return maven version
      run: mvn --version
