name: return Maven version
on: workflow_dispatch

jobs:
  build:
    runs-on: rhel-laptop-default
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: maven
    - name: Set up Maven
      run: |
        export MAVEN_HOME=/home/brentlipke/actions-runner/_work/_tool/apache-maven-3.9.9
        export PATH=$MAVEN_HOME/bin/:$PATH
        export MAVEN_OPTS="-Dmaven.repo.local=$RUNNER_TEMP/m2repo-${{ github.workflow_id }} -Djansi.tmpdir=$RUNNER_TEMP"
        mvn --version
    - name: return maven version
      run: mvn --version
