name: Smart Maven Cache Warmer (Serial Warm + Parallel Reuse)

on:
  workflow_dispatch:

jobs:
  warm-on-gh01:
    name: Warm Cache on rhel-laptop-default-gh01
    runs-on: rhel-laptop-default-gh01

    env:
      MAVEN_REPO: /home/brentlipke/actions-runner/seeds/m2-warm-cache

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare cache and temp folders
      run: |
        mkdir -p "$MAVEN_REPO"
        mkdir -p "${RUNNER_TEMP}/jansi-${GITHUB_RUN_ID}"
        mkdir -p "${RUNNER_TEMP}/tmp-${GITHUB_RUN_ID}"

    - name: Warm Maven cache
      run: |
        export MAVEN_HOME=/home/brentlipke/actions-runner/_work/_tool/apache-maven-3.9.9
        export PATH=$MAVEN_HOME/bin:$PATH
        export MAVEN_OPTS="
          -Dmaven.repo.local=$MAVEN_REPO
          -Djansi.tmpdir=${RUNNER_TEMP}/jansi-${GITHUB_RUN_ID}
          -Djava.io.tmpdir=${RUNNER_TEMP}/tmp-${GITHUB_RUN_ID}
        "
        mvn -B dependency:go-offline

    - name: Clean stale .lastUpdated files
      run: |
        find "$MAVEN_REPO" -name '*.lastUpdated' -delete

  reuse-on-gh02-gh03:
    name: Reuse Cache on gh02 and gh03
    needs: warm-on-gh01
    strategy:
      matrix:
        runner: ['rhel-laptop-default-gh02', 'rhel-laptop-default-gh03']

    runs-on: ${{ matrix.runner }}

    env:
      MAVEN_REPO: /home/brentlipke/actions-runner/seeds/m2-warm-cache

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare temp folders
      run: |
        mkdir -p "${RUNNER_TEMP}/jansi-${GITHUB_RUN_ID}"
        mkdir -p "${RUNNER_TEMP}/tmp-${GITHUB_RUN_ID}"

    - name: Build using warmed Maven cache
      run: |
        export MAVEN_HOME=/home/brentlipke/actions-runner/_work/_tool/apache-maven-3.9.9
        export PATH=$MAVEN_HOME/bin:$PATH
        export MAVEN_OPTS="
          -Dmaven.repo.local=$MAVEN_REPO
          -Djansi.tmpdir=${RUNNER_TEMP}/jansi-${GITHUB_RUN_ID}
          -Djava.io.tmpdir=${RUNNER_TEMP}/tmp-${GITHUB_RUN_ID}
        "
        mvn -B clean verify
