name: Maven Isolation Test

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner: ['rhel-laptop-default-gh01', 'rhel-laptop-default-gh02', 'rhel-laptop-default-gh03' ]

    name: Build on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: maven

    - name: Debug Verify Maven path and version
      run: |
          export MAVEN_HOME=/home/brentlipke/actions-runner/_work/_tool/apache-maven-3.9.9
          export PATH=$MAVEN_HOME/bin:$PATH
          export MAVEN_OPTS="-Dmaven.repo.local=$RUNNER_TEMP/m2repo-${{ github.run_id }} -Djansi.tmpdir=$RUNNER_TEMP"
          which mvn
          mvn --version
          echo "Using Maven from: $(which mvn)"
          mvn -version

    - name: Debug Verify Maven local repo location
      run: |
        export MAVEN_HOME=/home/brentlipke/actions-runner/_work/_tool/apache-maven-3.9.9
        export PATH=$MAVEN_HOME/bin:$PATH
        export MAVEN_OPTS="-Dmaven.repo.local=$RUNNER_TEMP/m2repo-${{ github.run_id }} -Djansi.tmpdir=$RUNNER_TEMP"
        echo "Using Maven local repo: $MAVEN_OPTS"
        echo "Effective maven.repo.local:"
        mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout

    - name: Build with Maven
      run: |
        export MAVEN_HOME=/home/brentlipke/actions-runner/_work/_tool/apache-maven-3.9.9
        export PATH=$MAVEN_HOME/bin:$PATH
        export MAVEN_OPTS="-Dmaven.repo.local=$RUNNER_TEMP/m2repo-${{ github.run_id }} -Djansi.tmpdir=$RUNNER_TEMP"
        echo "Using Maven local repo: $MAVEN_OPTS"
        echo "Effective maven.repo.local:"
        mvn clean install -X
