name: Maven Isolation Test

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner: ['rhel-laptop-default-gh01', 'rhel-laptop-default-gh02', 'rhel-laptop-default-gh03']

    name: Build on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: maven

    - name: Prep isolated temp folders
      run: |
        mkdir -p $RUNNER_TEMP/m2repo-${GITHUB_RUN_ID}
        mkdir -p $RUNNER_TEMP/jansi-${GITHUB_RUN_ID}
        mkdir -p $RUNNER_TEMP/java-tmp-${GITHUB_RUN_ID}

    - name: Verify Maven setup
      run: |
        export MAVEN_HOME=/home/brentlipke/actions-runner/_work/_tool/apache-maven-3.9.9
        export PATH=$MAVEN_HOME/bin:$PATH
        export MAVEN_OPTS="
          -Dmaven.repo.local=$RUNNER_TEMP/m2repo-${GITHUB_RUN_ID}
          -Djansi.tmpdir=$RUNNER_TEMP/jansi-${GITHUB_RUN_ID}
          -Djava.io.tmpdir=$RUNNER_TEMP/java-tmp-${GITHUB_RUN_ID}
        "
        echo "Maven path: $(which mvn)"
        mvn --version
        echo "MAVEN_OPTS: $MAVEN_OPTS"

    - name: Print effective Maven local repo
      run: |
        export MAVEN_HOME=/home/brentlipke/actions-runner/_work/_tool/apache-maven-3.9.9
        export PATH=$MAVEN_HOME/bin:$PATH
        export MAVEN_OPTS="
          -Dmaven.repo.local=$RUNNER_TEMP/m2repo-${GITHUB_RUN_ID}
          -Djansi.tmpdir=$RUNNER_TEMP/jansi-${GITHUB_RUN_ID}
          -Djava.io.tmpdir=$RUNNER_TEMP/java-tmp-${GITHUB_RUN_ID}
        "
        mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout

    - name: Build with Maven (and run tests)
      run: |
        export MAVEN_HOME=/home/brentlipke/actions-runner/_work/_tool/apache-maven-3.9.9
        export PATH=$MAVEN_HOME/bin:$PATH
        export MAVEN_OPTS="
          -Dmaven.repo.local=$RUNNER_TEMP/m2repo-${GITHUB_RUN_ID}
          -Djansi.tmpdir=$RUNNER_TEMP/jansi-${GITHUB_RUN_ID}
          -Djava.io.tmpdir=$RUNNER_TEMP/java-tmp-${GITHUB_RUN_ID}
        "
        mvn clean install -X
